# Generated by Django 2.2.16 on 2020-12-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200925_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
