# Generated by Django 2.2.16 on 2020-12-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_auto_20200925_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='techentry',
            name='link',
            field=models.TextField(default='www.link.com', max_length=1000),
            preserve_default=False,
        ),
    ]
