# Generated by Django 2.2.16 on 2021-01-06 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_techentry_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='techentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
